spring:
  application:
    name: item-trade
  jackson:
    time-zone: Asia/Seoul
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    timezone: Asia/Seoul
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
    resources:
      add-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3309/item_trade
    username: itemuser
    password: itempass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: d74a0fd3881f724cfac72c719b21f060
            client-secret: M18ZJOWbHqLw7nBPlKGogFsMSHZ4aSrO
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
              - birthday
              - birthyear
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          google:
            client-id: 17131993840-b1gajq42qaqlif3erqsnllho7qnf5g7d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
