name: item-trade CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: item_trade
        ports:
          - 3309:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: gradle/gradle-build-action@v2


      - name: Create application-test.yml
        run: |
          mkdir -p src/test/resources
          echo "spring:" > src/test/resources/application-test.yml
          echo "  datasource:" >> src/test/resources/application-test.yml
          echo "    url: jdbc:mysql://localhost:3309/item_trade" >> src/test/resources/application-test.yml
          echo "    username: root" >> src/test/resources/application-test.yml
          echo "    password: ${{ secrets.DB_PASSWORD }}" >> src/test/resources/application-test.yml
          echo "  security:" >> src/test/resources/application-test.yml
          echo "    oauth2:" >> src/test/resources/application-test.yml
          echo "      client:" >> src/test/resources/application-test.yml
          echo "        registration:" >> src/test/resources/application-test.yml
          echo "          kakao:" >> src/test/resources/application-test.yml
          echo "            client-id: ${{ secrets.KAKAO_ID }}" >> src/test/resources/application-test.yml
          echo "            client-secret: ${{ secrets.KAKAO_SECRET }}" >> src/test/resources/application-test.yml
          echo "            redirect-uri: http://localhost:8080/login/oauth2/code/kakao" >> src/test/resources/application-test.yml
          echo "          google:" >> src/test/resources/application-test.yml
          echo "            client-id: ${{ secrets.GOOGLE_ID }}" >> src/test/resources/application-test.yml
          echo "            client-secret: ${{ secrets.GOOGLE_SECRET }}" >> src/test/resources/application-test.yml
          echo "            redirect-uri: http://localhost:8080/login/oauth2/code/google" >> src/test/resources/application-test.yml

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test -Dspring.profiles.active=test --no-daemon
