name: item-trade CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      - name: Test SSH connection
#        run: |
#          echo "${{ secrets.EC2_SSH_KEY }}" > item.pem
#          chmod 600 item.pem
#          ssh -o StrictHostKeyChecking=no -i item.pem ec2-user@${{ secrets.EC2_HOST }} 'echo "SSH 연결 성공"'

      - name: Copy .jar to EC2
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIAVTE_KEY }}
          source: build/libs/item-trade-0.0.1-SNAPSHOT.jar
          target: ~/deploy/
          port: 22
          debug: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            pkill -f 'item-trade-0.0.1-SNAPSHOT.jar' || true
            cd ~/deploy
            tmux new-session -d -s itemtrade_session "sh -c '
              SPRING_PROFILES_ACTIVE=prod \
              DB_USERNAME=${{ secrets.DB_USERNAME }} \
              DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              KAKAO_ID=${{ secrets.KAKAO_ID }} \
              KAKAO_SECRET=${{ secrets.KAKAO_SECRET }} \
              GOOGLE_ID=${{ secrets.GOOGLE_ID }} \
              GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
              UPLOAD_DIR=/home/ec2-user/uploads/post \
              CHAT_DIR=/home/ec2-user/uploads/chat \
              java -jar item-trade-0.0.1-SNAPSHOT.jar > app.log 2>&1
            '"
            echo "✅ 배포 완료!"
     
