name: item-trade CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

#      - name: Test SSH connection
#        run: |
#          echo "${{ secrets.EC2_SSH_KEY }}" > item.pem
#          chmod 600 item.pem
#          ssh -o StrictHostKeyChecking=no -i item.pem ec2-user@${{ secrets.EC2_HOST }} 'echo "SSH 연결 성공"'

      - name: Copy .jar to EC2
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: build/libs/item-trade-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/deploy/build/libs/
          port: 22
          debug: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            pkill -f 'item-trade-0.0.1-SNAPSHOT.jar' || true
            echo "배포 시작"
            cat <<EOF > start.sh
            #!/bin/bash
            export SPRING_PROFILES_ACTIVE=prod
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export KAKAO_ID=${{ secrets.KAKAO_ID }}
            export KAKAO_SECRET=${{ secrets.KAKAO_SECRET }}
            export GOOGLE_ID=${{ secrets.GOOGLE_ID }}
            export GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
            export UPLOAD_DIR=/home/ec2-user/uploads/post
            export CHAT_DIR=/home/ec2-user/uploads/chat
            nohup java -jar /home/ec2-user/deploy/build/libs/item-trade-0.0.1-SNAPSHOT.jar > /home/ec2-user/deploy/app.log 2>&1 & disown
            EOF
            chmod +x start.sh
            ./start.sh

          
        
