name: item-trade CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Git commit information
        run: |
          git log -1 --oneline

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Check built JAR
        run: ls -l build/libs/

      - name: Remove old JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: rm -f /home/ec2-user/deploy/build/libs/item-trade-0.0.1-SNAPSHOT.jar

      - name: Copy .jar to EC2
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: build/libs/item-trade-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/deploy/build/libs/

      - name: Check JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: ls -l /home/ec2-user/deploy/build/libs/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            nohup /home/ec2-user/deploy/start.sh > /home/ec2-user/deploy/ci.log 2>&1 &
          # CD에서 JAR를 직접 실행시키지 않고, start.sh 스크립트를 통해 실행하기로 함.
